//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModel.AccoResource", typeof(AccoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is required.
        /// </summary>
        public static string Acco_Login_Required {
            get {
                return ResourceManager.GetString("Acco_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet requirements.
        /// </summary>
        public static string Acco_Password {
            get {
                return ResourceManager.GetString("Acco_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Acco_Password_Required {
            get {
                return ResourceManager.GetString("Acco_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure must be in the future.
        /// </summary>
        public static string AccoAvailablePeriod_Departure_Future {
            get {
                return ResourceManager.GetString("AccoAvailablePeriod_Departure_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the percentage is filled, the amount must be zero.
        /// </summary>
        public static string AccoPayPatternPayment_Amount {
            get {
                return ResourceManager.GetString("AccoPayPatternPayment_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the days after booking is filled, the days before arrival must be zero.
        /// </summary>
        public static string AccoPayPatternPayment_Days {
            get {
                return ResourceManager.GetString("AccoPayPatternPayment_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The days after booking or the days before arrival is required.
        /// </summary>
        public static string AccoPayPatternPayment_Days_Required {
            get {
                return ResourceManager.GetString("AccoPayPatternPayment_Days_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage or the amount is required.
        /// </summary>
        public static string AccoPayPatternPayment_Percentage_Required {
            get {
                return ResourceManager.GetString("AccoPayPatternPayment_Percentage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payments must be 100%.
        /// </summary>
        public static string AccoPayPatternPayment_Total100 {
            get {
                return ResourceManager.GetString("AccoPayPatternPayment_Total100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent is required.
        /// </summary>
        public static string AccoSeason_AccoRent_Required {
            get {
                return ResourceManager.GetString("AccoSeason_AccoRent_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season start and end must be in season year.
        /// </summary>
        public static string AccoSeason_Season_Year {
            get {
                return ResourceManager.GetString("AccoSeason_Season_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season may not overlap another.
        /// </summary>
        public static string AccoSeason_SeasonOverlap {
            get {
                return ResourceManager.GetString("AccoSeason_SeasonOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season start must before end.
        /// </summary>
        public static string AccoSeason_SeasonStart_SeasonEnd {
            get {
                return ResourceManager.GetString("AccoSeason_SeasonStart_SeasonEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season rent must be in seasonyear.
        /// </summary>
        public static string AccoSeason_SeasonYear_RentYear {
            get {
                return ResourceManager.GetString("AccoSeason_SeasonYear_RentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string ACCOTYPE_APARTMENT {
            get {
                return ResourceManager.GetString("ACCOTYPE_APARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalet.
        /// </summary>
        public static string ACCOTYPE_CHALET {
            get {
                return ResourceManager.GetString("ACCOTYPE_CHALET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Home.
        /// </summary>
        public static string ACCOTYPE_HOLIDAYHOME {
            get {
                return ResourceManager.GetString("ACCOTYPE_HOLIDAYHOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penthouse.
        /// </summary>
        public static string ACCOTYPE_PENTHOUSE {
            get {
                return ResourceManager.GetString("ACCOTYPE_PENTHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string ACCOTYPE_STUDIO {
            get {
                return ResourceManager.GetString("ACCOTYPE_STUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        public static string ACCOTYPE_VILLA {
            get {
                return ResourceManager.GetString("ACCOTYPE_VILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of adults must be greater than or equal to zero.
        /// </summary>
        public static string Booking_Adults {
            get {
                return ResourceManager.GetString("Booking_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arrival must be before the departure.
        /// </summary>
        public static string Booking_Arrival {
            get {
                return ResourceManager.GetString("Booking_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children must be greater than or equal to zero.
        /// </summary>
        public static string Booking_Children {
            get {
                return ResourceManager.GetString("Booking_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The departure must be in the future.
        /// </summary>
        public static string Booking_Departure_Future {
            get {
                return ResourceManager.GetString("Booking_Departure_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current booking overlaps with an existing booking.
        /// </summary>
        public static string Booking_Overlap {
            get {
                return ResourceManager.GetString("Booking_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pets must be greater than or equal to zero.
        /// </summary>
        public static string Booking_Pets {
            get {
                return ResourceManager.GetString("Booking_Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string BOOKINGSTATUS_CANCELLED {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string BOOKINGSTATUS_CLOSED {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string BOOKINGSTATUS_CONFIRMED {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string BOOKINGSTATUS_EXPIRED {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string BOOKINGSTATUS_PAID {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string BOOKINGSTATUS_RESERVED {
            get {
                return ResourceManager.GetString("BOOKINGSTATUS_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string COUNTRY_AUSTRIA {
            get {
                return ResourceManager.GetString("COUNTRY_AUSTRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string COUNTRY_BELGIUM {
            get {
                return ResourceManager.GetString("COUNTRY_BELGIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string COUNTRY_DENMARK {
            get {
                return ResourceManager.GetString("COUNTRY_DENMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England.
        /// </summary>
        public static string COUNTRY_ENGLAND {
            get {
                return ResourceManager.GetString("COUNTRY_ENGLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string COUNTRY_FRANCE {
            get {
                return ResourceManager.GetString("COUNTRY_FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string COUNTRY_GERMANY {
            get {
                return ResourceManager.GetString("COUNTRY_GERMANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        public static string COUNTRY_IRELAND {
            get {
                return ResourceManager.GetString("COUNTRY_IRELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string COUNTRY_ITALY {
            get {
                return ResourceManager.GetString("COUNTRY_ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourgh.
        /// </summary>
        public static string COUNTRY_LUXEMBOURGH {
            get {
                return ResourceManager.GetString("COUNTRY_LUXEMBOURGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string COUNTRY_NETHERLANDS {
            get {
                return ResourceManager.GetString("COUNTRY_NETHERLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string COUNTRY_NORWAY {
            get {
                return ResourceManager.GetString("COUNTRY_NORWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scotland.
        /// </summary>
        public static string COUNTRY_SCOTLAND {
            get {
                return ResourceManager.GetString("COUNTRY_SCOTLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string COUNTRY_SPAIN {
            get {
                return ResourceManager.GetString("COUNTRY_SPAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string COUNTRY_SWEDEN {
            get {
                return ResourceManager.GetString("COUNTRY_SWEDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwitserland.
        /// </summary>
        public static string COUNTRY_SWITSERLAND {
            get {
                return ResourceManager.GetString("COUNTRY_SWITSERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wales.
        /// </summary>
        public static string COUNTRY_WALES {
            get {
                return ResourceManager.GetString("COUNTRY_WALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland Franc.
        /// </summary>
        public static string CURRENCY_CHF {
            get {
                return ResourceManager.GetString("CURRENCY_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone.
        /// </summary>
        public static string CURRENCY_DKK {
            get {
                return ResourceManager.GetString("CURRENCY_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string CURRENCY_EURO {
            get {
                return ResourceManager.GetString("CURRENCY_EURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        public static string CURRENCY_GBP {
            get {
                return ResourceManager.GetString("CURRENCY_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway Krone.
        /// </summary>
        public static string CURRENCY_NOK {
            get {
                return ResourceManager.GetString("CURRENCY_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krone.
        /// </summary>
        public static string CURRENCY_SEK {
            get {
                return ResourceManager.GetString("CURRENCY_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        public static string CURRENCY_USD {
            get {
                return ResourceManager.GetString("CURRENCY_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following notifiations are available. 
        ///Go to  www.accobooking.nl to amend the booking reminders .....
        /// </summary>
        public static string email_NOTIFICATION_BODY {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on:.
        /// </summary>
        public static string email_NOTIFICATION_CREATED_ON {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_CREATED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string email_NOTIFICATION_FROM {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string email_NOTIFICATION_OWNER_NAME {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccoBooking notifications.
        /// </summary>
        public static string email_NOTIFICATION_SUBJECT {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string email_NOTIFICATION_TO {
            get {
                return ResourceManager.GetString("email_NOTIFICATION_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GENDER_FEMALE {
            get {
                return ResourceManager.GetString("GENDER_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GENDER_MALE {
            get {
                return ResourceManager.GetString("GENDER_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string GENDER_UNKNOWN {
            get {
                return ResourceManager.GetString("GENDER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail seems not correct.
        /// </summary>
        public static string Guest_Email_Format {
            get {
                return ResourceManager.GetString("Guest_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or phone must have a value.
        /// </summary>
        public static string Guest_EmailPhone_Required {
            get {
                return ResourceManager.GetString("Guest_EmailPhone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string lab_ACCO {
            get {
                return ResourceManager.GetString("lab_ACCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booker.
        /// </summary>
        public static string lab_BOOKER {
            get {
                return ResourceManager.GetString("lab_BOOKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to booking expired.
        /// </summary>
        public static string lab_BOOKING_EXPIRED {
            get {
                return ResourceManager.GetString("lab_BOOKING_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string lab_CONTEXT {
            get {
                return ResourceManager.GetString("lab_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lab_DESCRIPTION {
            get {
                return ResourceManager.GetString("lab_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string lab_DUE {
            get {
                return ResourceManager.GetString("lab_DUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest payment is scheduled.
        /// </summary>
        public static string lab_GUEST_PAYMENT_SCHEDULED {
            get {
                return ResourceManager.GetString("lab_GUEST_PAYMENT_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest payment is too late.
        /// </summary>
        public static string lab_GUEST_PAYMENT_TOO_LATE {
            get {
                return ResourceManager.GetString("lab_GUEST_PAYMENT_TOO_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license expires.
        /// </summary>
        public static string lab_LICENSE_EXPIRES {
            get {
                return ResourceManager.GetString("lab_LICENSE_EXPIRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The booking amount is not exactly scheduled.
        /// </summary>
        public static string lab_NOT_EXACTLY_SCHEDULED {
            get {
                return ResourceManager.GetString("lab_NOT_EXACTLY_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acco owner payment is scheduled.
        /// </summary>
        public static string lab_OWNER_PAYMENT_SCHEDULED {
            get {
                return ResourceManager.GetString("lab_OWNER_PAYMENT_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acco owner payment is too late.
        /// </summary>
        public static string lab_OWNER_PAYMENT_TOO_LATE {
            get {
                return ResourceManager.GetString("lab_OWNER_PAYMENT_TOO_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is scheduled.
        /// </summary>
        public static string lab_SCHEDULED {
            get {
                return ResourceManager.GetString("lab_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is too late.
        /// </summary>
        public static string lab_TOO_LATE {
            get {
                return ResourceManager.GetString("lab_TOO_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string LANGUAGE_DUTCH {
            get {
                return ResourceManager.GetString("LANGUAGE_DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANGUAGE_ENGLISH {
            get {
                return ResourceManager.GetString("LANGUAGE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string LANGUAGE_FRENCH {
            get {
                return ResourceManager.GetString("LANGUAGE_FRENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string LANGUAGE_GERMAN {
            get {
                return ResourceManager.GetString("LANGUAGE_GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string MAILTEMPLATE_ARRIVAL {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_ARRIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string MAILTEMPLATE_CANCELLATION {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MAILTEMPLATE_CONFIRMATION {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string MAILTEMPLATE_DEPARTURE {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment received.
        /// </summary>
        public static string MAILTEMPLATE_PAYMENTRECEIVED {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_PAYMENTRECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment reminder.
        /// </summary>
        public static string MAILTEMPLATE_PAYMENTREMINDER {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_PAYMENTREMINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period available.
        /// </summary>
        public static string MAILTEMPLATE_PERIODAVAILABLE {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_PERIODAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string MAILTEMPLATE_RESERVATION {
            get {
                return ResourceManager.GetString("MAILTEMPLATE_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string MILESTONE_ARRIVAL {
            get {
                return ResourceManager.GetString("MILESTONE_ARRIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string MILESTONE_BOOKING {
            get {
                return ResourceManager.GetString("MILESTONE_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string MILESTONE_DEPARTURE {
            get {
                return ResourceManager.GetString("MILESTONE_DEPARTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First payment.
        /// </summary>
        public static string MILESTONE_FIRST_PAYMENT {
            get {
                return ResourceManager.GetString("MILESTONE_FIRST_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last payment.
        /// </summary>
        public static string MILESTONE_LAST_PAYMENT {
            get {
                return ResourceManager.GetString("MILESTONE_LAST_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string MONTH_APRIL {
            get {
                return ResourceManager.GetString("MONTH_APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string MONTH_AUGUST {
            get {
                return ResourceManager.GetString("MONTH_AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string MONTH_DECEMBER {
            get {
                return ResourceManager.GetString("MONTH_DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string MONTH_FEBRUARY {
            get {
                return ResourceManager.GetString("MONTH_FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string MONTH_JANUARY {
            get {
                return ResourceManager.GetString("MONTH_JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string MONTH_JULY {
            get {
                return ResourceManager.GetString("MONTH_JULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string MONTH_JUNE {
            get {
                return ResourceManager.GetString("MONTH_JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string MONTH_MARCH {
            get {
                return ResourceManager.GetString("MONTH_MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MONTH_MAY {
            get {
                return ResourceManager.GetString("MONTH_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string MONTH_NOVEMBER {
            get {
                return ResourceManager.GetString("MONTH_NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string MONTH_OCTOBER {
            get {
                return ResourceManager.GetString("MONTH_OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string MONTH_SEPTEMBER {
            get {
                return ResourceManager.GetString("MONTH_SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival weekday is required when period is weekbased.
        /// </summary>
        public static string Period_ArrivalWeekDay_Required {
            get {
                return ResourceManager.GetString("Period_ArrivalWeekDay_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midweek.
        /// </summary>
        public static string PERIODUNIT_MIDWEEK {
            get {
                return ResourceManager.GetString("PERIODUNIT_MIDWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string PERIODUNIT_NIGHT {
            get {
                return ResourceManager.GetString("PERIODUNIT_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string PERIODUNIT_WEEK {
            get {
                return ResourceManager.GetString("PERIODUNIT_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string PERIODUNIT_WEEKEND {
            get {
                return ResourceManager.GetString("PERIODUNIT_WEEKEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        public static string PROVIDER_GMAIL {
            get {
                return ResourceManager.GetString("PROVIDER_GMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Mail.
        /// </summary>
        public static string PROVIDER_LIVE {
            get {
                return ResourceManager.GetString("PROVIDER_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        public static string PROVIDER_YAHOO {
            get {
                return ResourceManager.GetString("PROVIDER_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string UNIT_ADULT {
            get {
                return ResourceManager.GetString("UNIT_ADULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult per night.
        /// </summary>
        public static string UNIT_ADULT_PER_NIGHT {
            get {
                return ResourceManager.GetString("UNIT_ADULT_PER_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string UNIT_BOOKING {
            get {
                return ResourceManager.GetString("UNIT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string UNIT_CHILD {
            get {
                return ResourceManager.GetString("UNIT_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child per night.
        /// </summary>
        public static string UNIT_CHILD_PER_NIGHT {
            get {
                return ResourceManager.GetString("UNIT_CHILD_PER_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m3 gas.
        /// </summary>
        public static string UNIT_GASM3 {
            get {
                return ResourceManager.GetString("UNIT_GASM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWh.
        /// </summary>
        public static string UNIT_KWH {
            get {
                return ResourceManager.GetString("UNIT_KWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string UNIT_NIGHT {
            get {
                return ResourceManager.GetString("UNIT_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string UNIT_PERSON {
            get {
                return ResourceManager.GetString("UNIT_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person per night.
        /// </summary>
        public static string UNIT_PERSON_PER_NIGHT {
            get {
                return ResourceManager.GetString("UNIT_PERSON_PER_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet.
        /// </summary>
        public static string UNIT_PET {
            get {
                return ResourceManager.GetString("UNIT_PET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet per night.
        /// </summary>
        public static string UNIT_PET_PER_NIGHT {
            get {
                return ResourceManager.GetString("UNIT_PET_PER_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m3 water.
        /// </summary>
        public static string UNIT_WATER_M3 {
            get {
                return ResourceManager.GetString("UNIT_WATER_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string WEEKDAY_FRIDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string WEEKDAY_MONDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string WEEKDAY_SATURDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string WEEKDAY_SUNDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string WEEKDAY_THURSDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string WEEKDAY_TUESDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string WEEKDAY_WEDNESDAY {
            get {
                return ResourceManager.GetString("WEEKDAY_WEDNESDAY", resourceCulture);
            }
        }
    }
}
